site_name: Invoice Extractor Documentation
site_description: Documentation for the Invoice Extractor using Google's Gemini model
repo_url: https://github.com/ouassim-behlil/InvoiceDataExtractor
repo_name: ouassim-behlil/InvoiceDataExtractor
site_url: https://ouassim-behlil.github.io/InvoiceDataExtractor/
docs_dir: docs
site_dir: site
strict: true
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.copy
    - navigation.instant
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Documentation: api.md
  - Examples: examples.md
  - Validation: validation.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - include-markdown

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ouassim-behlil/InvoiceDataExtractor

extra_css:
  - stylesheets/extra.css
