name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Latest stable Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest tests/    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3.1.3
      with:
        name: pytest-results
        path: |
          .pytest_cache
          test-results/
          pytest-report.xml
        if-no-files-found: ignore
