name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Change to your preferred version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-generativeai
        pip install -r requirements.txt
        pip install pytest

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE/" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest